/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_demo;
import org.joda.time.LocalTime;
import org.apache.commons.lang3.SystemUtils;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        LocalTime currentTime = new LocalTime();
        System.out.println("The current local time is: " + currentTime);
        System.out.println("Current JDK Version is: " + SystemUtils.JAVA_SPECIFICATION_VERSION);
        System.out.println(new App().getGreeting());
    }
}
